### ISSUE TITLE
"TypeError: node.warn is not a function"

### ISSUE THREAD

**Issue by Unpuertomex** [linuxha/node-red-contrib-mytimeout#11]
Receiving the following error after upgrading to 2.2.2
"TypeError: node.warn is not a function"

Running node-red 0.19.1

**Comment by linuxha** [comment]
Odd, not sure why that is. That shouldn't be an error. Edit the node.warn("...."); and make it node.log("...");. It will skip the error but I can't recall what it will do to the functionality other than treat the message as an 'o'n condition.

That' supposed to be part of a  section of code that catches error in the newMsg handling. Do you have a sample of the message that you sent to the mytimeout node? I'm really going to need to look into this one. I haven't used 0.19.1, I have 0.19.0 and 0.19.2 is available.

At the moment you caught me in the middle of the float fix and updating the test scripts.

**Comment by linuxha** [comment]
I found the problem, it will be fixed in 2.2.3 but I'm working on other code now (I set node.warn to a value stomping on the function - oops). Using node.log is acceptable now as the desired behavior is to treat the message as an on condition (good comments for once ;-) ).

**Comment by Unpuertomex** [comment]
I reverted to 2.1.9 until you can get the fix. Thaks for looking into the error.

**Comment by linuxha** [comment]
This should now be fixed in version 3.0.1
